export enum BrazeBuildMyPortfolioEvents {
  CLICK_BUILD_PORTFOLIO = 'click build my portfolio',
  CLICK_BUY_CRYPTO_NOW = 'click buy crypto now',
  CLICK_PREQUALIFICATION_START = 'mp prequalification start click proceed',
  CLICK_PREQUALIFICATION_ACCREDITED_STATUS_NEXT = 'mp prequalification accredited status next',
  CLICK_PREQUALIFICATION_INVESTOR_PROFILE_NEXT = 'mp prequalification investor profile next',
  CLICK_PREQUALIFICATION_EXPERIENCE_NEXT = 'mp prequalification experience next',
  CLICK_PREQUALIFICATION_INVESTING_NEXT = 'mp prequalification investing next',
  NAVIGATION_PREQUALIFICATION_FAILURE = 'mp prequalification failure',
  CLICK_START_RISK_ASSESMENT = 'mp start risk assessment',
  CLICK_PREQUALIFICATION_FAILURE_GO_TO_MARKETWATCH = 'mp prequalification failure click go to marketwatch',
  NAVIGATION_PREQUALIFICATION_PASSED = 'mp prequalification passed',
  NAVIGATION_RISK_ASSESSMENT_COMPLETED = 'mp risk assessment complete',
  SLIDER_RISK_NUMBER = 'mp click change risk number slider',
  CLICK_CHANGE_NUMBER = 'mp click confirm change risk number',
  CLICK_FUND_PORTFOLIO = 'mp click fund portfolio',
  /* TODO: Implement event once screen is created */ CLICK_PROCEED_TO_IDENTITY_VERIFICATION = 'mp setup click proceed to identity verification',
  CLICK_PROCEED_TO_IDENTITY = 'mp setup click proceed to identity verification',
  NAVIGATION_IDENTITY_VERIFICATION_FAILURE = 'mp identity verification failure',
  CLICK_IDENTITY_FAILURE_CUSTOMER_SERVICE = 'mp identity verification failure click customer service',
  CLICK_CUSTOMER_SERVICE_SUBMIT_REQUEST = 'customer service click submit request',
  CLICK_PROCEED_TO_FUNDING = 'mp fund portfolio click proceed to funding',
  CLICK_FUND_CONFIRM_FUNDING = 'mp fund portfolio click confirm funding',
  CLICK_VIEW_MY_PORTFOLIO = 'mp click view my portfolio',
  /* TODO: Implement event once error is implemented */ NAVIGATION_NOT_ENOUGH_MONEY_ERROR = 'mp not enough money deposited error state',
  /* TODO: Implement event once error is implemented */ CLICK_CANCEL_NOT_ENOUGH_MONEY = 'mp not enough money deposited click cancel and refund',
}
