export const enum AmplitudeManagedPortfolioEvents {
  CLICK_CLOSE_PORTFOLIO = 'mp close portfolio click proceed ',
  CLICK_CLOSE_PORTFOLIO_CONFIRM = 'mp close portfolio confirm and transfer assets ',
  CLICK_ERROR_PAGE_CANCEL = 'close mp error page click cancel',
  CLICK_CONFIRM_RETAKE_RISK = 'mp click confirm retake risk assessment',
  CLICK_CONFIRM_NEW_PORTFOLIO = 'mp retake risk assessment click confirm new portfolio',
  CLICK_DISCARD_NEW_PORTFOLIO = 'mp retake risk assessment click discard new portfolio',
  CLOSE = 'mp click close portfolio',
  RETAKE_ASSESSMENT = 'mp click retake risk assessment',
  ADD_FUNDS = 'mp click add funds',
  CLICK_FUND_PORTFOLIO = 'mp click fund portfolio',
  CLICK_PORTFOLIO_COMPONENT = 'mp click portfolio component',
  CLICK_PROCEED_TO_VERIFICATION = 'mp setup click proceed to identity verification',
  CLICK_FUND_PORTFOLIO_SELECT_OPTION = 'mp fund portfolio click proceed to funding',
  CLICK_CONFIRM_FUNDING = 'mp fund portfolio click confirm funding',
  CLICK_GENERATE_WALLET = 'crypto deposit click generate address',
  /* TODO: Implement event once error is implemented */ NAVIGATION_NOT_ENOUGH_MONEY_ERROR = 'mp not enough money deposited error state',
  /* TODO: Implement event once error is implemented */ CLICK_CANCEL_NOT_ENOUGH_MONEY = 'mp not enough money deposited click cancel and refund',
}
