// Auto-generated file created by react-native-storybook-loader
// Do not edit.
//
// https://github.com/elderfo/react-native-storybook-loader.git

function loadStories() {
  require('../app/components/AccrualCard/__stories__/index.story');
  require('../app/components/AllAssetsCard/__stories__/index.story');
  require('../app/components/AmountHeaderCard/__stories__/index.story');
  require('../app/components/AmountInput/__stories__/index.story');
  require('../app/components/AssetsEmptyState/__stories__/index.story');
  require('../app/components/AssetsItem/__stories__/index.story');
  require('../app/components/AssetsVariationTable/__stories__/index.story');
  require('../app/components/AssetVariationItem/__stories__/index.story');
  require('../app/components/Background/__stories__/index.story');
  require('../app/components/Badge/__stories__/index.story');
  require('../app/components/BottomSheetModal/__stories__/index.story');
  require('../app/components/Buttons/ActionButton/__stories__/index.story');
  require('../app/components/Buttons/BadgeButton/__stories__/index.story');
  require('../app/components/Buttons/Button/__stories__/index.story');
  require('../app/components/Buttons/CryptoButton/__stories__/index.story');
  require('../app/components/Buttons/IconButton/__stories__/index.story');
  require('../app/components/Buttons/SecretValuesButton/__stories__/index.story');
  require('../app/components/Buttons/TextButton/__stories__/index.story');
  require('../app/components/CandleStickBarChart/__stories__/index.story');
  require('../app/components/Card/__stories__/index.story');
  require('../app/components/Checkbox/__stories__/index.story');
  require('../app/components/CodeInput/__stories__/index.story');
  require('../app/components/CoinCard/__stories__/index.story');
  require('../app/components/CoinIcon/__stories__/index.story');
  require('../app/components/CoinStack/__stories__/index.story');
  require('../app/components/CoinStackCard/__stories__/index.story');
  require('../app/components/CoinWithExchangeIcon/__stories__/index.story');
  require('../app/components/CollapsibleText/__stories__/index.story');
  require('../app/components/ContainerWithScrollableHeader/__stories__/index.story');
  require('../app/components/CopyWalletAddress/__stories__/index.story');
  require('../app/components/CryptoValueLabel/__stories__/index.story');
  require('../app/components/CustomSpinner/__stories__/index.story');
  require('../app/components/Divider/__stories__/index.story');
  require('../app/components/ExchangeCard/__stories__/index.story');
  require('../app/components/ExchangeIcon/__stories__/index.story');
  require('../app/components/ExchangesCarousel/__stories__/index.story');
  require('../app/components/GemCard/__stories__/index.story');
  require('../app/components/HeaderSwap/__stories__/index.story');
  require('../app/components/Icon/__stories__/index.story');
  require('../app/components/Indicators/__stories__/index.story');
  require('../app/components/IndividualCoinsCard/__stories__/index.story');
  require('../app/components/Chart/__stories__/index.story');
  require('../app/components/LineChart/__stories__/index.story');
  require('../app/components/Link/__stories__/index.story');
  require('../app/components/List/__stories__/index.story');
  require('../app/components/ListButton/__stories__/index.story');
  require('../app/components/ListNavigationItem/__stories__/index.story');
  require('../app/components/LoadingModal/__stories__/index.story');
  require('../app/components/Logo/__stories__/index.story');
  require('../app/components/ModalContent/__stories__/index.story');
  require('../app/components/MultiSelect/__stories__/index.story');
  require('../app/components/News/__stories__/index.story');
  require('../app/components/NewsArticle/__stories__/index.story');
  require('../app/components/PaymentMethodOption/__stories__/index.story');
  require('../app/components/PeriodButton/__stories__/index.story');
  require('../app/components/Quantity/__stories__/index.story');
  require('../app/components/RadioButton/__stories__/index.story');
  require('../app/components/RiskAppetiteCard/__stories__/index.story');
  require('../app/components/RiskCard/__stories__/index.story');
  require('../app/components/RiskGroupTable/__stories__/index.story');
  require('../app/components/RiskSlider/__stories__/index.story');
  require('../app/components/SearchInput/__stories__/index.story');
  require('../app/components/Select/__stories__/index.story');
  require('../app/components/SimpleHeader/__stories__/index.story');
  require('../app/components/Slider/__stories__/index.story');
  require('../app/components/SliderThumb/__stories__/index.story');
  require('../app/components/SlideShow/__stories__/index.story');
  require('../app/components/StackedBarChart/__stories__/index.story');
  require('../app/components/StickyHeader/__stories__/index.story');
  require('../app/components/Tabs/__stories__/index.story');
  require('../app/components/TabViews/__stories__/index.story');
  require('../app/components/TextInput/__stories__/index.story');
  require('../app/components/Toggle/__stories__/index.story');
  require('../app/components/ToggleIcons/__stories__/index.story');
  require('../app/components/ToggleLabeled/__stories__/index.story');
  require('../app/components/Tooltip/__stories__/index.story');
  require('../app/components/TransactionsCard/__stories__/index.story');
  require('../app/components/Typography/__stories__/index.story');
  require('../app/components/ValueLabel/__stories__/index.story');
  require('../app/components/WaitingIndicator/__stories__/index.story');
  require('../app/modals/CoinSelection/__stories__/index.story');
}

const stories = [
  '../app/components/AccrualCard/__stories__/index.story',
  '../app/components/AllAssetsCard/__stories__/index.story',
  '../app/components/AmountHeaderCard/__stories__/index.story',
  '../app/components/AmountInput/__stories__/index.story',
  '../app/components/AssetsEmptyState/__stories__/index.story',
  '../app/components/AssetsItem/__stories__/index.story',
  '../app/components/AssetsVariationTable/__stories__/index.story',
  '../app/components/AssetVariationItem/__stories__/index.story',
  '../app/components/Background/__stories__/index.story',
  '../app/components/Badge/__stories__/index.story',
  '../app/components/BottomSheetModal/__stories__/index.story',
  '../app/components/Buttons/ActionButton/__stories__/index.story',
  '../app/components/Buttons/BadgeButton/__stories__/index.story',
  '../app/components/Buttons/Button/__stories__/index.story',
  '../app/components/Buttons/CryptoButton/__stories__/index.story',
  '../app/components/Buttons/IconButton/__stories__/index.story',
  '../app/components/Buttons/SecretValuesButton/__stories__/index.story',
  '../app/components/Buttons/TextButton/__stories__/index.story',
  '../app/components/CandleStickBarChart/__stories__/index.story',
  '../app/components/Card/__stories__/index.story',
  '../app/components/Checkbox/__stories__/index.story',
  '../app/components/CodeInput/__stories__/index.story',
  '../app/components/CoinCard/__stories__/index.story',
  '../app/components/CoinIcon/__stories__/index.story',
  '../app/components/CoinStack/__stories__/index.story',
  '../app/components/CoinStackCard/__stories__/index.story',
  '../app/components/CoinWithExchangeIcon/__stories__/index.story',
  '../app/components/CollapsibleText/__stories__/index.story',
  '../app/components/ContainerWithScrollableHeader/__stories__/index.story',
  '../app/components/CopyWalletAddress/__stories__/index.story',
  '../app/components/CryptoValueLabel/__stories__/index.story',
  '../app/components/CustomSpinner/__stories__/index.story',
  '../app/components/Divider/__stories__/index.story',
  '../app/components/ExchangeCard/__stories__/index.story',
  '../app/components/ExchangeIcon/__stories__/index.story',
  '../app/components/ExchangesCarousel/__stories__/index.story',
  '../app/components/GemCard/__stories__/index.story',
  '../app/components/HeaderSwap/__stories__/index.story',
  '../app/components/Icon/__stories__/index.story',
  '../app/components/Indicators/__stories__/index.story',
  '../app/components/IndividualCoinsCard/__stories__/index.story',
  '../app/components/Chart/__stories__/index.story',
  '../app/components/LineChart/__stories__/index.story',
  '../app/components/Link/__stories__/index.story',
  '../app/components/List/__stories__/index.story',
  '../app/components/ListButton/__stories__/index.story',
  '../app/components/ListNavigationItem/__stories__/index.story',
  '../app/components/LoadingModal/__stories__/index.story',
  '../app/components/Logo/__stories__/index.story',
  '../app/components/ModalContent/__stories__/index.story',
  '../app/components/MultiSelect/__stories__/index.story',
  '../app/components/News/__stories__/index.story',
  '../app/components/NewsArticle/__stories__/index.story',
  '../app/components/PaymentMethodOption/__stories__/index.story',
  '../app/components/PeriodButton/__stories__/index.story',
  '../app/components/Quantity/__stories__/index.story',
  '../app/components/RadioButton/__stories__/index.story',
  '../app/components/RiskAppetiteCard/__stories__/index.story',
  '../app/components/RiskCard/__stories__/index.story',
  '../app/components/RiskGroupTable/__stories__/index.story',
  '../app/components/RiskSlider/__stories__/index.story',
  '../app/components/SearchInput/__stories__/index.story',
  '../app/components/Select/__stories__/index.story',
  '../app/components/SimpleHeader/__stories__/index.story',
  '../app/components/Slider/__stories__/index.story',
  '../app/components/SliderThumb/__stories__/index.story',
  '../app/components/SlideShow/__stories__/index.story',
  '../app/components/StackedBarChart/__stories__/index.story',
  '../app/components/StickyHeader/__stories__/index.story',
  '../app/components/Tabs/__stories__/index.story',
  '../app/components/TabViews/__stories__/index.story',
  '../app/components/TextInput/__stories__/index.story',
  '../app/components/Toggle/__stories__/index.story',
  '../app/components/ToggleIcons/__stories__/index.story',
  '../app/components/ToggleLabeled/__stories__/index.story',
  '../app/components/Tooltip/__stories__/index.story',
  '../app/components/TransactionsCard/__stories__/index.story',
  '../app/components/Typography/__stories__/index.story',
  '../app/components/ValueLabel/__stories__/index.story',
  '../app/components/WaitingIndicator/__stories__/index.story',
  '../app/modals/CoinSelection/__stories__/index.story',
];

module.exports = {
  loadStories,
  stories,
};
