export const CHART_DEFAULT_PADDING = 30;
export const CHART_DEFAULT_RIGHT_PADDING = 16;

export const NUMBER_OF_LABELS = 6;
export const NUMBER_OF_GRIDS = NUMBER_OF_LABELS * 2;

export const GRADIENT_FIRST_OFFSET = '0%';

export const GRADIENT_FIRST_STOP_OPACITY = 0.15;
export const GRADIENT_SECOND_STOP_OPACITY = 0.15;
export const GRADIENT_THIRD_STOP_OPACITY = 0.15;
export const SOLID_STOP_OPACITY = 1;

export const GRADIENT_SECOND_DIVISOR = 10;
export const GRADIENT_THIRD_DIVISOR = 5;

export const LABEL_DEFAULT_PADDING = 0;
export const LABEL_DEFAULT_SPACING = 0;

export const GRID_DEFAULT_INTERVAL = 30;
export const GRID_DEFAULT_HORIZONTAL_PADDING = 20;
export const GRID_DEFAULT_VERTICAL_PADDING = 20;

export const LINE_DEFAULT_STROKE_WIDTH = 2;

export const PAN_GESTURE_STATE = {
  UNDETERMINED: 0,
  FAILED: 1,
  BEGAN: 2,
  CANCELLED: 3,
  ACTIVE: 4,
  END: 5,
};

export const TOOLTIP_FIXED_HEIGHT = 66;
export const TOOLTIP_FIXED_WIDTH = 110;
export const CIRCLE_MARKER_RADIUS = 5;
export const DISTANCE_BETWEEN_TOOLTIP_CIRCLE = 12;
export const RELATIVE_HEIGHT_BETWEEN_TOOLTIP_AND_CIRCLE =
  DISTANCE_BETWEEN_TOOLTIP_CIRCLE + CIRCLE_MARKER_RADIUS + TOOLTIP_FIXED_HEIGHT;

export const FORMAT_CURRENCY_REGEX = /\B(?=(\d{3})+(?!\d))/g;
